
# Source .tmux.conf as suggested in `man tmux`
bind R source-file '~/.config/tmux/tmux.conf'

# Plugin manager

run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'

# Plugins
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
# Better clipboard
set -g @plugin 'laktak/extrakto'
