
# Source .tmux.conf as suggested in `man tmux`
bind R source-file '~/.config/tmux/tmux.conf'

# Allowing mouse edit of size
set-option -g mouse on

# make scrolling with wheels work
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
# Do not sync panes so we dont have inputs sent to multiple panes
setw -g synchronize-panes off
# Plugin manager

run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'


# Plugins
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
# Better clipboard
set -g @plugin 'laktak/extrakto'
